# Generated by Django 4.2.2 on 2025-04-01 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Nombre del jugador')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='País')),
                ('lichess_username', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Nombre de usuario en Lichess')),
                ('lichess_rating_bullet', models.IntegerField(default=0, verbose_name='Rating Bullet en Lichess')),
                ('lichess_rating_blitz', models.IntegerField(default=0, verbose_name='Rating Blitz en Lichess')),
                ('lichess_rating_rapid', models.IntegerField(default=0, verbose_name='Rating Rapid en Lichess')),
                ('lichess_rating_classical', models.IntegerField(default=0, verbose_name='Rating Classical en Lichess')),
                ('fide_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID FIDE')),
                ('fide_rating_blitz', models.IntegerField(default=0, verbose_name='Rating Blitz FIDE')),
                ('fide_rating_rapid', models.IntegerField(default=0, verbose_name='Rating Rapid FIDE')),
                ('fide_rating_classical', models.IntegerField(default=0, verbose_name='Rating Classical FIDE')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'unique_together': {('email', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RankingSystemClass',
            fields=[
                ('value', models.CharField(choices=[('BU', 'Buchholz'), ('BC', 'Buchholz Cut 1'), ('BA', 'Buchholz Average'), ('SB', 'Sonneborn-Berger'), ('PS', 'Plain Score'), ('WI', 'No. Wins'), ('BT', 'No. games played with Black')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('referee_number', models.CharField(default='-1', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Nombre del torneo')),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha de finalización')),
                ('max_update_time', models.IntegerField(default=43200, verbose_name='Tiempo máximo para actualizar resultados (segundos)')),
                ('only_administrative', models.BooleanField(default=False, verbose_name='Solo el administrador puede modificar juegos')),
                ('tournament_type', models.CharField(choices=[('SR', 'Round Robin Simple'), ('DR', 'Round Robin Doble'), ('DD', 'Round Robin Doble (mismo día)'), ('SW', 'Sistema Suizo')], max_length=2, verbose_name='Tipo de torneo')),
                ('tournament_speed', models.CharField(choices=[('BU', 'Bullet'), ('BL', 'Blitz'), ('RA', 'Rápido'), ('CL', 'Clásico')], max_length=2, verbose_name='Velocidad del torneo')),
                ('board_type', models.CharField(choices=[('LIC', 'lichess'), ('OTB', 'over the board')], max_length=3, verbose_name='Tipo de tablero')),
                ('win_points', models.FloatField(default=1.0, verbose_name='Puntos por victoria')),
                ('draw_points', models.FloatField(default=0.5, verbose_name='Puntos por empate')),
                ('lose_points', models.FloatField(default=0.0, verbose_name='Puntos por derrota')),
                ('timeControl', models.CharField(default='15+0', max_length=32, verbose_name='Control de tiempo')),
                ('number_of_rounds_for_swiss', models.IntegerField(default=0, verbose_name='Número de rondas para torneos suizos')),
                ('administrativeUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario administrador')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('registration_order', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.tournament')),
            ],
            options={
                'ordering': ['registration_order'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, through='chess_models.TournamentPlayers', to='chess_models.player', verbose_name='Jugadores participantes'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rankingList',
            field=models.ManyToManyField(blank=True, to='chess_models.rankingsystemclass', verbose_name='Sistemas de clasificación asociados'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess_models.referee', verbose_name='Árbitro del torneo'),
        ),
    ]
