# Generated by Django 4.2.2 on 2025-04-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre de la ronda')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('fnish', models.BooleanField(default=False, verbose_name='¿Ronda finalizada?')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='chess_models.tournament', verbose_name='Torneo')),
            ],
        ),
    ]
