# Generated by Django 4.2.2 on 2025-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayers',
            name='registration_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden de registro'),
        ),
    ]
