# Generated by Django 4.2.2 on 2025-05-08 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0002_alter_tournamentplayers_registration_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_rounds_for_swiss',
            field=models.IntegerField(default=0, verbose_name='Número de rondas para torneos swiss'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
