# Generated by Django 4.2.2 on 2025-04-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0002_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='Partida finalizada')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('result', models.CharField(choices=[('w', 'White'), ('b', 'Black'), ('=', 'Draw'), ('+', 'Forfeit win'), ('-', 'Forfeit loss'), ('H', 'Half point bye'), ('F', 'Full point bye'), ('U', 'Unpaired game point bye'), ('Z', 'Zero point bye'), ('*', 'No available')], default='*', max_length=1, verbose_name='Resultado')),
                ('ranking_order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Orden de clasificación')),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='chess_models.player', verbose_name='Jugador con negras')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='chess_models.round', verbose_name='Ronda')),
                ('white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='chess_models.player', verbose_name='Jugador con blancas')),
            ],
        ),
    ]
