# Generated by Django 4.2.2 on 2025-04-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0003_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', through='chess_models.TournamentPlayers', to='chess_models.player'),
        ),
        migrations.AlterField(
            model_name='tournamentplayers',
            name='registration_order',
            field=models.IntegerField(help_text='Orden en que el jugador se unió al torneo', verbose_name='Orden de registro'),
        ),
    ]
