# Generated by Django 5.2.1 on 2025-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0003_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', through='chess_models.TournamentPlayers', through_fields=('tournament', 'player'), to='chess_models.player'),
        ),
    ]
