# Generated by Django 4.2.2 on 2025-04-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0004_alter_tournament_players_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentplayers',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayers',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tournamentplayers',
            name='registration_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden de registro'),
        ),
    ]
