# Generated by Django 4.2.2 on 2025-04-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0005_alter_tournamentplayers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nombre del árbitro'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='referee_number',
            field=models.CharField(default='-1', max_length=32, verbose_name='Número de árbitro'),
        ),
    ]
