# Generated by Django 4.2.2 on 2025-04-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0006_alter_referee_name_alter_referee_referee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referee',
            old_name='referee_number',
            new_name='refereeNumber',
        ),
    ]
