# Generated by Django 4.2.2 on 2025-04-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0007_rename_referee_number_referee_refereenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='chess_models.player', verbose_name='Jugador con negras'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='chess_models.player', verbose_name='Jugador con blancas'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_set', to='chess_models.tournament', verbose_name='Torneo asociado'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rankingList',
            field=models.ManyToManyField(blank=True, related_name='rounds', to='chess_models.rankingsystemclass', verbose_name='Sistemas de clasificación asociados'),
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_rounds',
            field=models.ManyToManyField(blank=True, related_name='tournament_schedules', through='chess_models.TournamentRound', to='chess_models.round', verbose_name='Rondas programadas'),
        ),
    ]
