# Generated by Django 4.2.2 on 2025-04-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0008_alter_game_black_alter_game_white_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_rounds',
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_set',
            field=models.ManyToManyField(blank=True, related_name='round_set', through='chess_models.TournamentRound', to='chess_models.round', verbose_name='Rondas programadas'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_set', to='chess_models.tournament', verbose_name='Torneo asociado'),
        ),
    ]
